repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        exclude: alembic/
  - repo: https://github.com/psf/black
    rev: 23.9.1 
    hooks:
      - id: black
        exclude: (frontend/|controller/)
