"""empty message

Revision ID: 161451529395
Revises: 2b5a8d870c60
Create Date: 2025-03-16 17:32:19.890033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161451529395'
down_revision: Union[str, None] = '2b5a8d870c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('humidity', 'uuid')
    op.drop_column('temperature', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature', sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('humidity', sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
