"""empty message

Revision ID: 2b5a8d870c60
Revises: 7d7558be659d
Create Date: 2025-03-07 20:39:19.490439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b5a8d870c60"
down_revision: Union[str, None] = "7d7558be659d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "soundlevel",
        sa.Column("created_at_timestamp", sa.Integer(), nullable=False),
        sa.Column("sound_level", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("created_at_timestamp"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("soundlevel")
    # ### end Alembic commands ###
