"""empty message

Revision ID: 7d7558be659d
Revises: 
Create Date: 2025-01-19 14:59:56.363572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7558be659d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('humidity',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at_timestamp', sa.Integer(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('temperature',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at_timestamp', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperature')
    op.drop_table('humidity')
    # ### end Alembic commands ###
